# fly.toml file generated for hannesdiem on 2022-01-29T22:02:11+01:00

app = "hannesdiem"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"
  CYPRESS_INSTALL_BINARY = "0"
  NODE_ENV = "production"
  FLY = "true"
  PRIMARY_REGION = "fra"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  destination = "/app/.cache"
  source = "image_cache"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
